config/routes.rb
# frozen_string_literal: true

require 'api/api'
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'statistics/show'
  resource :profile, only: [:show, :update] do
    member do
      put :reset_private_token
    end
  end

  resources :hosts, only: [:show, :update]
  resources :current_host_stats, only: :index
  resources :usage_data, only: [:new, :create, :show] do
    collection do
      get 'months'
      post 'schedule_backfill'
    end
  end

  resources :metrics, only: [:index, :show], constraints: { id: /[A-Za-z_0-9]+/ }
  resources :versions, except: :show
  resources :usage_ping_errors, only: [:create]
  resources :usage_ping_metadata, only: [:create]

  get 'check(.:format)',
      to: 'version_checks#check',
      defaults: { format: 'png' },
      constraints: { format: /png|svg|json/ }

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'versions#index'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
  end
end

app/models/current_host_stat.rb
# frozen_string_literal: true

class CurrentHostStat < ApplicationRecord
  include Sortable
  include UserCounters

  belongs_to :host

  scope :with_host, -> { includes(:host).references(:host) }
  scope :with_usage_datum, -> { where.not(usage_data_recorded_at: nil) }
  scope :starred, -> { with_host.merge(Host.starred) }
  scope :fortune_companies, -> { with_host.merge(Host.fortune_companies) }
  scope :by_license, ->(md5) { where(license_md5: md5) }
  scope :by_edition, ->(edition) { where(edition: edition) }
  scope :by_url, ->(url) { where(arel_table[:url].matches("%#{sanitize_sql_like(url)}%")) }

  delegate :fortune_rank, to: :host

  class << self
    def to_csv(view_context)
      csv_attributes = %w[
        host_id host_link active_users_count historical_max_users_count user_count version
        usage_data_recorded_at edition
      ]
      CSV.generate(headers: true) do |csv|
        csv << csv_attributes

        all.csv_limit.each do |current_host_stat| # Not using find_each to preserve applied limit and sorting
          csv << csv_attributes.map do |attr|
            if current_host_stat.attributes.include?(attr)
              current_host_stat.attributes[attr]
            elsif attr == 'host_link' && view_context.respond_to?(:host_url)
              view_context.host_url(current_host_stat.host)
            end
          end
        end
      end
    end

    def csv_limit
      limit(1000)
    end

    def find_or_create_for_usage_data!(host, usage_data)
      safe_find_or_create_by!(url: host.url) do |record|
        record.host_id = host.id
        record.host_created_at = host.created_at
        record.usage_data_recorded_at = usage_data.recorded_at
        record.active_users_count = usage_data.active_user_count
        record.historical_max_users_count = usage_data.historical_max_users
        record.user_count = usage_data.license_user_count
        record.license_md5 = usage_data.license_md5
        record.version = usage_data.version
        record.edition = usage_data.edition
      end
    end
  end

  def customers_account?
    zuora_account_id.present?
  end
end

app/controllers/current_host_stats_controller.rb
# frozen_string_literal: true

class CurrentHostStatsController < ApplicationController
  helper_method :sort_column,
                :sort_direction

  def index
    @current_host_stats = CurrentHostStat.with_host.with_usage_datum
    @current_host_stats = @current_host_stats.starred if params[:starred].present?
    @current_host_stats = @current_host_stats.fortune_companies if params[:fortune_rank].present?
    @current_host_stats = @current_host_stats.by_edition(params[:edition]) if params[:edition].present?
    @current_host_stats = by_search_type if search_applied?
    @current_host_stats = @current_host_stats.order_by(sort_column, sort_direction)

    respond_to do |format|
      format.html do
        @current_host_stats = @current_host_stats.page(params[:page]).per(params[:per])
      end
      format.csv do
        send_data @current_host_stats.to_csv(view_context), filename: "version-gitlab-hosts-#{Date.today}.csv"
      end
    end
  end

  private

  def search_applied?
    params[:search].present?
  end

  def by_search_type
    if license_search?
      @current_host_stats.by_license(params[:search])
    else
      @current_host_stats.by_url(params[:search])
    end
  end

  def license_search?
    params[:search_type] == 'License MD5'
  end

  def sort_column
    params[:sort] || 'url'
  end

  def sort_direction
    params[:direction] || 'desc'
  end
end

app/helpers/current_host_stats_helper.rb
# frozen_string_literal: true

module CurrentHostStatsHelper
  def search_sortable_column(column:, title: nil, default_order: 'asc')
    title, column, direction, css_class = calculate_sorting(column, title, default_order)

    link_to title,
            {
              sort: column,
              direction: direction
            }.merge(search_params)
              .merge(applied_filters),
            {
              class: css_class
            }
  end

  def search_params
    {
      search: params[:search],
      search_type: params[:search_type]
    }.compact
  end

  def applied_filters
    {
      starred: params[:starred],
      fortune_rank: params[:fortune_rank],
      edition: params[:edition]
    }.compact
  end

  def filter_params
    {
      sort: sort_column,
      direction: sort_direction
    }.merge(search_params)
  end

  def dropdown_edition_option_class(edition)
    ['dropdown-item', (:active if params[:edition] == edition)]
  end

  def edition_filter_text
    params[:edition] || 'All'
  end

  def dropdown_button_class
    [:btn, 'dropdown-toggle', "btn-#{'outline-' if params[:starred] || params[:fortune_rank]}secondary"]
  end

  def dropdown_all_editions_option_class
    ['dropdown-item', (:active unless params[:edition])]
  end

  def starred_link_class
    [:btn, "btn-#{'outline-' unless params[:starred]}secondary"]
  end

  def fortune_rank_link_class
    [:btn, "btn-#{'outline-' unless params[:fortune_rank]}secondary"]
  end

  def licensed_user_count(record)
    count_text = record.user_count.presence || 'unknown'

    link_to_if(
      record.customers_account?,
      count_text,
      "#{Rails.configuration.application.customers_admin_url}/billing_account?query=#{record.zuora_account_id}",
      {
        data: { toggle: 'tooltip' },
        title: 'Link to admin this billing account on the Customers Application.'
      }
    )
  end
end

app/views/current_host_stats/index.html.haml
- search_filter_text = params[:search_type] || 'Host URL'
.row.pb-2
  %h2.col-1
    Hosts
  .col-5
    .btn-group
      .btn-group
        = button_tag "Edition: #{edition_filter_text}",
          type: 'button',
          class: dropdown_button_class,
          data: { toggle: 'dropdown' }
        .dropdown-menu
          = link_to 'Edition: All', filter_params, class: dropdown_all_editions_option_class
          - UsageData::EDITIONS.each do |edition|
            = link_to "Edition: #{edition}", filter_params.merge(edition: edition), class: dropdown_edition_option_class(edition)
      = link_to 'Starred only', filter_params.merge(starred: true), class: starred_link_class
      = link_to 'Fortune companies only', filter_params.merge(fortune_rank: true), class: fortune_rank_link_class
      = link_to 'Download CSV', filter_params.merge(applied_filters, format: 'csv'), class: 'btn btn-outline-secondary'
  .col
    = form_for current_host_stats_path, method: :get, html: { class: 'form-inline float-right' } do
      .input-group
        = select_tag 'search_type',
          options_for_select(['Host URL', 'License MD5'], search_filter_text),
          class: 'border border-secondary custom-select'
        .input-group-append
          = search_field_tag :search, params[:search], class: 'form-control current_host_stats-search rounded-0'
        = hidden_field_tag :sort, sort_column
        = hidden_field_tag :direction, sort_direction
        = hidden_field_tag :starred, params[:starred] if params[:starred]
        = hidden_field_tag :fortune_rank, params[:fortune_rank] if params[:fortune_rank]
        = hidden_field_tag :edition, params[:edition] if params[:edition]
        .input-group-append
          = button_tag 'Search', class: 'btn btn-secondary'

%table.table.table-striped.hosts.pretty.small
  %thead
    %tr
      %th= search_sortable_column column: 'url', title: 'Host URL'
      %th= search_sortable_column column: 'active_users_count', title: 'Active User Count', default_order: 'desc'
      %th= search_sortable_column column: 'historical_max_users_count', default_order: 'desc'
      %th= search_sortable_column column: 'user_count', title: 'Licensed User Count', default_order: 'desc'
      %th= search_sortable_column column: 'version', default_order: 'desc'
      %th= search_sortable_column column: 'usage_data_recorded_at', title: 'Service Ping Last Checked On', default_order: 'desc'
      %th= search_sortable_column column: 'host_created_at', title: 'Created At', default_order: 'desc'
      %th Star
      %th Fortune Rank

  %tbody
    - @current_host_stats.each do |current_host_stat|
      %tr
        %td
          = link_to host_path(current_host_stat.host) do
            = current_host_stat.url
        %td= current_host_stat.active_users_count
        %td= current_host_stat.historical_max_users_count
        %td
          = licensed_user_count(current_host_stat)
          - if current_host_stat.usage_users
            %span{ class: license_usage_class(current_host_stat) }== (#{license_usage_users(current_host_stat)})
        %td= current_host_stat.version
        %td= current_host_stat.usage_data_recorded_at&.to_date
        %td= current_host_stat.host_created_at.to_date
        %td
          = form_for current_host_stat.host, url: host_path(current_host_stat.host), remote: true, html: { class: 'star-host' } do |f|
            = f.check_box :star, class: 'trigger-star', id: "host_star_#{current_host_stat.id}"
            = f.submit 'Save', class: 'submit'
        %td= current_host_stat.fortune_rank
%hr
= paginate @current_host_stats, theme: 'bootstrap4'
#{@current_host_stats.total_count} hosts with Usage Datum.

:javascript
  $(document).ready(function() {
    $('.trigger-star').on('click', function() {
      return $(this).parent().find('.submit').click();
    });

    $(".star-host").on("ajax:success", function() {
      return $(this).parent().effect("highlight");
    });
    $('[data-toggle="tooltip"]').tooltip();
  });