config/routes.rb
# frozen_string_literal: true

require 'api/api'
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'statistics/show'
  resource :profile, only: [:show, :update] do
    member do
      put :reset_private_token
    end
  end

  resources :hosts, only: [:show, :update]
  resources :current_host_stats, only: :index
  resources :usage_data, only: [:new, :create, :show] do
    collection do
      get 'months'
      post 'schedule_backfill'
    end
  end

  resources :metrics, only: [:index, :show], constraints: { id: /[A-Za-z_0-9]+/ }
  resources :versions, except: :show
  resources :usage_ping_errors, only: [:create]
  resources :usage_ping_metadata, only: [:create]

  get 'check(.:format)',
      to: 'version_checks#check',
      defaults: { format: 'png' },
      constraints: { format: /png|svg|json/ }

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'versions#index'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
  end
end

app/models/version.rb
# frozen_string_literal: true
class Version < ApplicationRecord
  PERMITTED_VERSION = /\d+\.\d+\.\d+/.freeze

  has_many :features
  has_many :usage_ping_errors

  enum vulnerability_type: { not_vulnerable: 0, non_critical: 1, critical: 2 }

  validates :version,
            presence: true,
            uniqueness: true,
            format: { with: /\A#{PERMITTED_VERSION}\Z/, message: "should be X.X.X" }
  validates :details, length: { maximum: 2048 }

  scope :most_recent, -> { order(id: :desc) }
  scope :most_recent_by_version, -> { order(Arel.sql("string_to_array(version, '.')::integer[] DESC")) }
  scope :within, ->(version) { where("version LIKE ?", ParsedVersion.new(version).to_query) }

  # When :security_release_type is marked as :non_critical or :critical
  #   :mark_previous_versions_vulnerable will execute logic to mark previous
  #   versions with the correct vulnerability_type.
  attr_accessor :security_release_type

  before_save :mark_previous_versions_vulnerable

  def self.resolve!(version_or_id)
    version_or_id.to_s.start_with?('v') ? latest(version_or_id, raise_exception: true) : find(version_or_id)
  end

  def self.latest_minor_releases_after(count:, after_version:)
    latest_minor_releases(count).select do |version_object|
      VersionSorter.compare(version_object.version, after_version) == 1
    end
  end

  def self.latest_minor_releases(count)
    versions = Version.pluck(:version)

    # find the highest patch version for each minor version
    last_feature_versions = ::VersionSorter.rsort(versions).uniq do |version|
      version.split('.').take(2)
    end.take(count)

    VersionSorter.rsort(Version.where(version: last_feature_versions).to_a, &:version)
  end

  def self.latest(version = nil, raise_exception: false)
    scope = version ? Version.within(version) : Version
    last_version = VersionSorter.sort(scope.pluck(:version)).last # rubocop:disable Style/RedundantSort

    if raise_exception
      Version.find_by!(version: last_version)
    else
      Version.find_by(version: last_version)
    end
  end

  def self.latest?(version)
    latest_version = latest.version
    begin
      parsed = ParsedVersion.new(version)
      VersionSorter.compare(parsed.to_s, ParsedVersion.new(latest_version).to_s(parsed.precision)) >= 0
    rescue ParsedVersion::InvalidVersionError
      VersionSorter.compare(version, latest_version) >= 0
    end
  end

  def major
    parsed_version.major.to_i
  end

  def minor
    parsed_version.minor.to_i
  end

  private

  def parsed_version
    ParsedVersion.new(version)
  end

  def mark_previous_versions_vulnerable
    return unless security_patch?

    previous_versions = Version.within(parsed_version.to_s(:minor))

    case security_release_type
    when 'critical'
      previous_versions.update_all(vulnerability_type: security_release_type) # rubocop:disable Rails/SkipsModelValidations
    when 'non_critical'
      previous_versions.where.not(vulnerability_type: :critical).update_all(vulnerability_type: security_release_type) # rubocop:disable Rails/SkipsModelValidations
    end
  end

  def security_patch?
    return false if security_release_type.blank?

    security_release_type != 'not_vulnerable'
  end
end

app/controllers/versions_controller.rb
# frozen_string_literal: true

class VersionsController < ApplicationController
  before_action :set_version, only: [:edit, :update, :destroy]

  def index
    @versions = Version.most_recent_by_version
    @versions = @versions.page(params[:page])
  end

  def new
    @version = Version.new
    @version.version = params[:version] if params[:version].present?
  end

  def edit; end

  def create
    @version = Version.new(version_params)

    respond_to do |format|
      if @version.save
        format.html { redirect_to versions_path, notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @version }
      else
        format.html { render :new }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to versions_path, notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: @version }
      else
        format.html { render :edit }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @version.destroy

    respond_to do |format|
      format.html { redirect_to versions_path, status: :found, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_version
    @version = Version.find(params[:id])
  end

  def version_params
    params.require(:version).permit(:version, :vulnerability_type, :security_release_type, :details)
  end
end

app/helpers/version_helper.rb
# frozen_string_literal: true

module VersionHelper
  def vulnerability_type_options_for_select
    Version.vulnerability_types.keys.map { |k| [vulnerability_type_ui_label(k), k] }
  end

  private

  def vulnerability_type_ui_label(key)
    if key == 'not_vulnerable'
      'No'
    else
      key.titleize
    end
  end
end

app/views/versions/_form.html.haml
= form_for @version do |f|
  - if @version.errors.any?
    #error_explanation
      %h2= "#{pluralize(@version.errors.count, "error")} prohibited this version from being saved:"
      %ul
        - @version.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :version
    = f.text_field :version, class: 'form-control', autofocus: 'autofocus'
  .form-group
    = f.label :details
    = f.text_area :details, class: 'form-control', rows: 12
  .form-row.ml-0
    .form-group
      - if @version.persisted?
        = f.label :vulnerability_type, 'Vulnerable version?'
        .small.text-muted.mb-1
          A vulnerability requires immediate update.
        = f.select :vulnerability_type, vulnerability_type_options_for_select, {}, { class: 'custom-select col-md-8' }
      - else
        = f.label :security_release_type, 'Security release?'
        .small.text-muted.mb-1
          Marks all previous versions of the same monthly release with selection.
        = f.select :security_release_type, vulnerability_type_options_for_select, {}, { class: 'custom-select col-md-6' }
  %hr
  .form-group
    = f.submit 'Save', class: 'btn btn-success'

= link_to 'Back', versions_path

app/views/versions/edit.html.haml
%h1 Editing version

= render 'form'

app/views/versions/index.html.haml
%h2.pb-2
  Versions
  .float-right
    = link_to 'New Version', new_version_path, class: 'btn btn-secondary'

%table.table.table-striped
  %thead
    %tr
      %th Version
      %th Vulnerability Type
      %th Additional details
      %th Created at
      %th

  %tbody
    - @versions.each do |version|
      %tr
        %td= version.version
        - if version.not_vulnerable?
          %td
            No
        - else
          %td.alert-danger
            = version.vulnerability_type.titleize
        %td.w-50
          - if version.details.present?
            %div
              %button.btn.btn-link{type: "button", 'data-toggle' => "collapse",
               "data-target"=>"#collapseDetails_#{version.id}"} Details
            %div.pt-2.collapse{id: "collapseDetails_#{version.id}"}
              %div.card.card-body
                = sanitize version.details
        %td= version.created_at.to_s
        %td.text-right
          = link_to 'Edit', edit_version_path(version)
          \|
          = link_to 'Destroy', version, method: :delete, data: { confirm: 'Are you sure?' }

%hr
= paginate @versions, theme: 'bootstrap4'

app/views/versions/new.html.haml
%h1 New version

= render 'form'