config/routes.rb
# frozen_string_literal: true

require 'api/api'
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'statistics/show'
  resource :profile, only: [:show, :update] do
    member do
      put :reset_private_token
    end
  end

  resources :hosts, only: [:show, :update]
  resources :current_host_stats, only: :index
  resources :usage_data, only: [:new, :create, :show] do
    collection do
      get 'months'
      post 'schedule_backfill'
    end
  end

  resources :metrics, only: [:index, :show], constraints: { id: /[A-Za-z_0-9]+/ }
  resources :versions, except: :show
  resources :usage_ping_errors, only: [:create]
  resources :usage_ping_metadata, only: [:create]

  get 'check(.:format)',
      to: 'version_checks#check',
      defaults: { format: 'png' },
      constraints: { format: /png|svg|json/ }

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'versions#index'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
  end
end

app/models/usage_data.rb
# frozen_string_literal: true

class UsageData < ApplicationRecord
  serialize :licensee, JSON # rubocop:disable Cop/ActiveRecordSerialize
  serialize :license_add_ons, JSON # rubocop:disable Cop/ActiveRecordSerialize

  belongs_to :host, optional: true
  belongs_to :raw_usage_data, optional: true

  has_one :conversational_development_index
  has_one :avg_cycle_analytics, class_name: 'AvgCycleAnalytics', inverse_of: :usage_data

  scope :related_weekly_user_count_by_uuid, (lambda do |uuid|
    where(uuid: uuid).group_by_week(:created_at).maximum(:active_user_count)
  end)
  scope :related_stats_by_week, (lambda do |uuid, host_id, metric|
    where(uuid: uuid, host_id: host_id)
      .group_by_week(:recorded_at)
      .maximum(sanitize_sql_for_conditions(["(stats::json->>:metric)::int", metric: metric]))
  end)
  scope :recent_counts_by_month_edition, (lambda do
    select("date_trunc('month', recorded_at) as month, COALESCE(edition, 'EE') as computed_edition, COUNT(*) as count")
      .where(UsageData.arel_table[:recorded_at].gt(6.months.ago))
      .group(:month, :computed_edition)
      .order(month: :desc)
  end)
  scope(:ordered_and_paginated, ->(page, per) { order(id: :desc).page(page).per(per) })
  scope :ordered_by_id_with_limit, ->(rows) { order(id: :desc).limit(rows) }
  scope :by_uuid_with_recorded_limits, (lambda do |uuid, time_range|
    where(uuid: uuid, recorded_at: time_range).order(:recorded_at)
  end)
  scope :ids_by_edition_with_created_limits, (lambda do |edition, time_range|
    where(created_at: time_range, edition: edition).ids
  end)
  scope :by_uuid, ->(uuid) { where(uuid: uuid) }
  scope :uniq_gitlab_versions, -> { pluck(:version).uniq.reject(&:blank?) }

  CE_EDITION = 'CE'
  EE_EDITION = 'EE'
  EE_EDITIONS = ['EE Free', 'EES', 'EE', 'EEP', 'EEU'].freeze
  EDITIONS = ([CE_EDITION] + EE_EDITIONS).freeze

  def initialize(data = nil)
    data = clean_data(data || {})

    super(data)
  end

  def licensee_company
    licensee&.dig('Company')
  end

  def licensee_name
    licensee&.dig('Name')
  end

  def licensee_email
    licensee&.dig('Email')
  end

  def usage_users
    return unless has_user_count?

    historical_max_users - license_user_count
  end

  def over?
    has_user_count? && (historical_max_users > license_user_count)
  end

  def has_user_count?
    license_user_count.to_i.positive?
  end

  # Not every service ping has an edition, because this was only added when we
  # added CE service pings. So `nil` always means EE, and we don't know the exact
  # edition.
  def edition
    super || EE_EDITION
  end

  def ce?
    edition == CE_EDITION
  end

  def ee?
    !ce?
  end

  def related_weekly_user_count_by_uuid
    self.class.related_weekly_user_count_by_uuid(uuid)
  end

  private

  def clean_data(data)
    # Fix typo in 8.12.0
    if data.dig(:stats, :protected_branchess)
      data['stats']['protected_branches'] = data['stats'].delete('protected_branchess')
    end

    data
  end
end

app/controllers/usage_data_controller.rb
# frozen_string_literal: true

class UsageDataController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create
  skip_before_action :authenticate_user!, only: [:create, :new]
  before_action :set_default_json_format, only: :create

  def new; end

  def show
    @usage_data =
      if /^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$/.match?(params[:id])
        UsageData.by_uuid(params[:id]).ordered_by_id_with_limit(1).last
      else
        UsageData.find(params[:id])
      end
  end

  def create
    if (uploaded_file = params[:service_usage_data_file])
      data = JSON.parse(uploaded_file.read)
      params[:usage_datum] = data
    end

    raw_usage_data = save_original_usage_ping

    response = UsagePing::ServiceHandler.new.execute(
      usage_data_params.to_h, request.remote_ip, raw_usage_data&.id
    )

    track_event(upload_successful: true)

    respond_to do |format|
      format.html do
        redirect_to new_usage_datum_path, notice: 'Service usage data was successfully uploaded.'
      end
      format.json { render json: response, status: :created }
    end

  rescue ActiveRecord::RecordInvalid, UsagePing::StatsParser::NonIntegerError
    track_event(upload_successful: false)

    respond_to do |format|
      format.json { render json: {}, status: :unprocessable_entity }
    end
  rescue StandardError
    track_event(upload_successful: false)

    flash[:upload_failed] = true
    respond_to do |format|
      format.html { redirect_to new_usage_datum_path, alert: 'There was an error processing uploaded file.' }
    end
  end

  def months
    @month_counts = UsageDataByMonthService.new.execute
  end

  def schedule_backfill
    count = Salesforce::BackfillService.new(params[:month_editions]).execute
    flash[:notice] = "Scheduled #{count} jobs"

    redirect_to months_usage_data_path
  end

  private

  # ServicePing gets submitted without `Accept: "application/json"` in the header.
  # To not break behaviour for GitLab instances that expect a JSON response, we default to JSON.
  def set_default_json_format
    request.format = :json unless request.media_type == Mime[:multipart_form]
  end

  def usage_data_params
    filtered_payload.permit(*usage_param_keys).tap do |whitelisted|
      # Whitelist entire hashes
      # https://github.com/rails/rails/blob/v4.2.7/guides/source/action_controller_overview.md#outside-the-scope-of-strong-parameters
      whitelisted_hash_keys.each do |key|
        whitelisted[key] = filtered_payload[key].permit! if filtered_payload[key].present?
      end

      # Even if we change the payload that GitLab EE is sending,
      # we need to handle both and will have to do so forever to
      # support old GitLab installations.
      whitelisted[:stats] = filtered_payload[:counts].permit! if filtered_payload[:counts].present?
    end
  end

  def usage_param_keys
    UsagePing::USAGE_DATA_PARAMS +
      UsagePing::FEATURES_PARAMS
  end

  def whitelisted_hash_keys
    UsagePing::COMPONENTS_PARAMS +
      UsagePing::CYCLE_ANALYTICS_PARAMS +
      UsagePing::LICENSE_PARAMS +
      UsagePing::SYSTEM_USAGE_PARAMS +
      UsagePing::SMAU_PARAMS +
      UsagePing::OBJECT_STORE_PARAMS +
      UsagePing::TOPOLOGY_PARAMS +
      UsagePing::SETTINGS_PARAMS +
      UsagePing::UNIQUE_VISITS_PARAMS
  end

  def save_original_usage_ping
    RawUsageData.create(
      uuid: filtered_payload[:uuid],
      recorded_at: filtered_payload[:recorded_at],
      payload: filtered_payload,
      raw_usage_data_payload: params[:usage_datum]
    )
  end

  def filtered_payload
    return @filtered_payload if defined?(@filtered_payload)

    usage_params = UsagePing::FixParams.new.execute(params[:usage_datum])
    @filtered_payload = UsagePing::FilterUsageDataService.new(usage_params).execute
  end

  def track_event(event_data)
    return unless params[:service_usage_data_file] # we only track manual uploads

    EventTracker.new.track("service_ping_manual_upload", event_data)
  end
end

app/helpers/usage_data_helper.rb
# frozen_string_literal: true

module UsageDataHelper
  def license_trial_description(trial)
    case trial
    when true
      'Yes'
    when false
      'No'
    when nil
      'Unknown'
    end
  end

  def license_usage_class(record)
    record.over? ? 'license-over' : 'license-under'
  end

  def license_usage_users(record)
    usage_users = record.usage_users
    return usage_users unless record.over?

    "+#{record.usage_users}"
  end
end

app/views/usage_data/months.html.haml
%h2 Service ping totals by month

%p
  Select months and editions, then submit to send usage data to Salesforce. (Any
  data that was already sent will not be duplicated.) Because of the
  = link_to('Salesforce API limits', 'https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_api.htm')
  scheduling more than 100,000 on a single day is not recommended.

%p
  To view job status, see the
  = succeed '.' do
    = link_to('Sidekiq dashboard', '/sidekiq')

= form_tag(schedule_backfill_usage_data_path, method: :post) do
  %table.table.table-striped.pretty
    %thead
      %tr
        %th Month
        - UsageData::EDITIONS.each do |edition|
          %th= edition
    %tbody
      - @month_counts.each do |month, counts|
        %tr
          %td= month
          - UsageData::EDITIONS.each do |edition|
            - count = counts[edition] || 0
            - check_box_value = "#{month}-#{edition}"
            %td
              = label_tag(check_box_value, count)
              = check_box_tag('month_editions[]', check_box_value, false, disabled: count.zero?, id: check_box_value, class: 'js-month-checkbox', data: { count: count })

  %p= submit_tag('Schedule backfill', class: 'js-month-submit')

= javascript_include_tag 'months'

app/views/usage_data/new.html.haml
- if flash[:upload_failed]
  .alert.alert-danger{:style => "margin-top: 20px;"}
    %strong
      If there are problems with the manual upload:
    %ol{:style => "margin-top: 10px;"}
      %li Open a confidential issue in the <a href="https://gitlab.com/gitlab-org/security/version.gitlab.com">security fork of version app project.</a>
      %li Attach the JSON payload if possible.
      %li Tag `@gitlab-org/analytics-section/analytics-instrumentation` who will triage the issue.
      
%h1 Service usage data

%div
  = form_with url: usage_data_path do |f|
    .form-group
      = f.label :service_usage_data_file, 'Upload Service usage data file generated by your Gitlab instance'
      = f.file_field :service_usage_data_file, class: 'form-control-file', autofocus: 'autofocus', accept: 'application/json'
    %hr
    .form-group
      = f.submit 'Upload', class: 'btn btn-success'

%small The uploaded file is encrypted and sent using secure <a href="https://en.wikipedia.org/wiki/HTTP">HTTPS protocol</a>.<br />HTTPS creates a secure communication channel between the web browser and the server, and protects transmitted data against man-in-the-middle attacks.

app/views/usage_data/show.html.haml
= render 'metrics/modal'

- if @usage_data&.ee?
  .row
    .col-12
      .last-ping-date.float-right== Data received at #{@usage_data.created_at}
      %h3= @usage_data.licensee_company || @usage_data.licensee_name
      %hr

      %p
        %span.title Licensee name:
        %span= @usage_data.licensee_name
      %p
        %span.title Licensee email:
        %span= @usage_data.licensee_email
      %p
        %span.title Licensee MD5:
        %span= @usage_data.license_md5
      %p
        %span.title Licensee SHA256:
        %span= @usage_data.license_sha256
      %p
        %span.title License will expire at
        %span= @usage_data.license_expires_at
      %p
        %span.title GitLab version:
        %span= @usage_data.version
      %p
        %span.title Trial?
        %span= license_trial_description(@usage_data.license_trial)
.row
  - if @usage_data
    .col-12
      .card
        .card-header
          %p
            %span.title Hostname:
            - if @usage_data.hostname.present?
              %span= @usage_data.hostname
            - else
              %span data not available
          %p
            %span.title UUID:
            - if @usage_data.uuid.present?
              %span= @usage_data.uuid
            - else
              %span data not available
          %p
            %span.title GitLab version:
            %span= @usage_data.version
          %p
            %span.title GitLab edition:
            - if @usage_data.edition.present?
              %span= @usage_data.edition.upcase
            - else
              %span data not available
          %p
            %span.title GitLab installation type:
            - if @usage_data.installation_type.present?
              %span= @usage_data.installation_type
            - else
              %span data not available
          %p
            %span.title Mattermost enabled:
            - if @usage_data.mattermost_enabled.present?
              %span= @usage_data.mattermost_enabled
            - else
              %span data not available
          %p
            %span.title Data received at:
            %span= @usage_data.created_at
        - convdev_index = @usage_data.conversational_development_index
        - if convdev_index
          .card-body
            .row
              .col-12
                %h3 Conversational Development Index
                %table.table.table-striped.pretty
                  %thead
                    %tr
                      %th
                      %th Boards
                      %th CI Pipelines
                      %th Deployments
                      %th Environments
                      %th Issues
                      %th Merge Requests
                      %th Milestones
                      %th Notes
                      %th Projects Prometheus
                      %th Service Desk Issues
                  %tbody
                    %tr
                      %td Leader
                      %td= convdev_index.leader_boards
                      %td= convdev_index.leader_ci_pipelines
                      %td= convdev_index.leader_deployments
                      %td= convdev_index.leader_environments
                      %td= convdev_index.leader_issues
                      %td= convdev_index.leader_merge_requests
                      %td= convdev_index.leader_milestones
                      %td= convdev_index.leader_notes
                      %td= convdev_index.leader_projects_prometheus_active
                      %td= convdev_index.leader_service_desk_issues
                    %tr
                      %td Instance
                      %td= convdev_index.instance_boards
                      %td= convdev_index.instance_ci_pipelines
                      %td= convdev_index.instance_deployments
                      %td= convdev_index.instance_environments
                      %td= convdev_index.instance_issues
                      %td= convdev_index.instance_merge_requests
                      %td= convdev_index.instance_milestones
                      %td= convdev_index.instance_notes
                      %td= convdev_index.instance_projects_prometheus_active
                      %td= convdev_index.instance_service_desk_issues
                    %tr
                      %td.title Percentage
                      %td #{convdev_index.percentage_boards.round(1)} %
                      %td #{convdev_index.percentage_ci_pipelines.round(1)} %
                      %td #{convdev_index.percentage_deployments.round(1)} %
                      %td #{convdev_index.percentage_environments.round(1)} %
                      %td #{convdev_index.percentage_issues.round(1)} %
                      %td #{convdev_index.percentage_merge_requests.round(1)} %
                      %td #{convdev_index.percentage_milestones.round(1)} %
                      %td #{convdev_index.percentage_notes.round(1)} %
                      %td #{convdev_index.percentage_projects_prometheus_active.round(1)} %
                      %td #{convdev_index.percentage_service_desk_issues.round(1)} %

        .card-body
          .row
            .col-12
              %h3 User count
              %hr

              %p
                %span.title Active User Count:
                %span= @usage_data.active_user_count
              %p
                %span.title License Restricted User Count:
                %span= @usage_data.license_user_count
                - if @usage_data.usage_users
                  %span{ class: license_usage_class(@usage_data) }== (#{license_usage_users(@usage_data)})
              %p
                %span.title Historical Max Users Count:
                %span= @usage_data.historical_max_users

              .users-chart-wrapper
                = line_chart(@usage_data.related_weekly_user_count_by_uuid)

            .col-12
              %h3 Usage Counts
              %hr

              - if @usage_data.stats.present?
                %p Each line in this service ping indicates the total number of objects in the database, per feature, since the introduction of said feature (`.count` method in Ruby). Deleted objects are not taken into account for the calculation.

                %table.table.table-striped
                  %thead
                    %tr
                      %th statistic
                      %th value
                      %th p. project
                      %th p. group
                  %tbody
                    - @usage_data.stats.each do |metric, counter|
                      %tr
                        %td= link_to metric,
                            metric_path(uuid: @usage_data.uuid, host_id: @usage_data.host_id, id: metric),
                            remote: true,
                            class: 'metric-modal'
                        %td= number_with_delimiter(counter, delimiter: ' ')
                        %td= number_with_precision((counter / @usage_data.stats["projects"].to_f), precision: 2)
                        %td= number_with_precision((counter / @usage_data.stats["groups"].to_f), precision: 2)

              - else
                %p
                  Usage data counts not available.

        .card-body
          .row
            .col-12
              %h3 Usage data json fields
              %hr
                %p below is raw data from each field entry
                %table.table.table-striped
                  %thead
                    %tr
                      %th column
                      %th value
                  %tbody
                    %tr
                      %td object_store
                      %td= @usage_data.object_store
                    %tr
                      %td topology
                      %td= @usage_data.topology
                    %tr
                      %td counts_weekly
                      %td= @usage_data.counts_weekly
                    %tr
                      %td counts_monthly
                      %td= @usage_data.counts_monthly
                    %tr
                      %td usage_activity_by_stage
                      %td= @usage_data.usage_activity_by_stage
                    %tr
                      %td usage_activity_by_stage_monthly
                      %td= @usage_data.usage_activity_by_stage_monthly

  - else
    .col-12
      %p
        Usage data not available.