config/routes.rb
# frozen_string_literal: true

require 'api/api'
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'statistics/show'
  resource :profile, only: [:show, :update] do
    member do
      put :reset_private_token
    end
  end

  resources :hosts, only: [:show, :update]
  resources :current_host_stats, only: :index
  resources :usage_data, only: [:new, :create, :show] do
    collection do
      get 'months'
      post 'schedule_backfill'
    end
  end

  resources :metrics, only: [:index, :show], constraints: { id: /[A-Za-z_0-9]+/ }
  resources :versions, except: :show
  resources :usage_ping_errors, only: [:create]
  resources :usage_ping_metadata, only: [:create]

  get 'check(.:format)',
      to: 'version_checks#check',
      defaults: { format: 'png' },
      constraints: { format: /png|svg|json/ }

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'versions#index'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %title GitLab - Versions
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = include_gon
  %body
    .navbar.navbar-expand-lg.navbar-light.bg-light
      .container-fluid
        %a.navbar-brand{ href: root_path } version.gitlab.com
        %button.navbar-toggler{ type: "button", data: { toggle: "collapse", target: '#navbarNav' }, 'aria-controls': 'navbarSupportedContent', 'aria-expanded': false, 'aria-label': 'Toggle navigation' }
          %span.navbar-toggler-icon

        #navbarNav.collapse.navbar-collapse
          - if current_user
            %ul.nav.navbar-nav
              = nav_link 'Versions', versions_path
              = nav_link 'Hosts', current_host_stats_path
              = nav_link 'Usage Statistics', metrics_path
              = nav_link 'Statistics', statistics_show_path
            %ul.nav.navbar-nav.ml-auto
              %li
                = link_to profile_path, class: 'nav-link' do
                  = current_user.email
              %li
                = link_to destroy_user_session_path, class: 'nav-link logout', method: :delete, title: 'Sign out' do
                  Logout
          - else
            %ul.nav.navbar-nav.ml-auto
              %li
                = link_to "Sign in with GitLab", user_gitlab_omniauth_authorize_path, method: :post
    .container-fluid.mt-3
      - if alert.present?
        .alert.alert-danger= alert
      - if notice.present?
        .alert.alert-info= notice
      = yield